name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Authentication Succeeded
        run: echo "Authentication Succeeded"
      - name: Build the Docker image
        run: docker build -t mocisco/simple-nextjs-app:latest .
      - name: Authenticate with Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN}} | docker login -u ${{ secrets.DOCKERHUB_USERNAME}} --password-stdin

      - name: Push the Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME}}/simple-nextjs-app:latest
        